<?php
/**
 * SemanticsAbsCoords
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * SemanticsAbsCoords Class Doc Comment
 *
 * @category    Class
 * @description Bounding box of element, in pixels.
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SemanticsAbsCoords implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'x0' => 'int',
        'x1' => 'int',
        'y0' => 'int',
        'y1' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'x0' => 'x0',
        'x1' => 'x1',
        'y0' => 'y0',
        'y1' => 'y1'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'x0' => 'setX0',
        'x1' => 'setX1',
        'y0' => 'setY0',
        'y1' => 'setY1'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'x0' => 'getX0',
        'x1' => 'getX1',
        'y0' => 'getY0',
        'y1' => 'getY1'
    );
  
    
    /**
      * $x0 Left border of bounding box.
      * @var int
      */
    protected $x0;
    
    /**
      * $x1 Right border of bounding box.
      * @var int
      */
    protected $x1;
    
    /**
      * $y0 Top of bounding box.
      * @var int
      */
    protected $y0;
    
    /**
      * $y1 Bottom of bounding box.
      * @var int
      */
    protected $y1;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->x0 = $data["x0"];
            $this->x1 = $data["x1"];
            $this->y0 = $data["y0"];
            $this->y1 = $data["y1"];
        }
    }
    
    /**
     * Gets x0
     * @return int
     */
    public function getX0()
    {
        return $this->x0;
    }
  
    /**
     * Sets x0
     * @param int $x0 Left border of bounding box.
     * @return $this
     */
    public function setX0($x0)
    {
        
        $this->x0 = $x0;
        return $this;
    }
    
    /**
     * Gets x1
     * @return int
     */
    public function getX1()
    {
        return $this->x1;
    }
  
    /**
     * Sets x1
     * @param int $x1 Right border of bounding box.
     * @return $this
     */
    public function setX1($x1)
    {
        
        $this->x1 = $x1;
        return $this;
    }
    
    /**
     * Gets y0
     * @return int
     */
    public function getY0()
    {
        return $this->y0;
    }
  
    /**
     * Sets y0
     * @param int $y0 Top of bounding box.
     * @return $this
     */
    public function setY0($y0)
    {
        
        $this->y0 = $y0;
        return $this;
    }
    
    /**
     * Gets y1
     * @return int
     */
    public function getY1()
    {
        return $this->y1;
    }
  
    /**
     * Sets y1
     * @param int $y1 Bottom of bounding box.
     * @return $this
     */
    public function setY1($y1)
    {
        
        $this->y1 = $y1;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
