<?php
/**
 * InlineResponse200
 *
 * PHP version 5
 *
 * @category Class
 * @package  Organizeme\Xtractor
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Organizeme\Xtractor\Models;

use \ArrayAccess;
/**
 * InlineResponse200 Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Organizeme\Xtractor
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200 implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'best_candidate' => '\Organizeme\Xtractor\Models\ContentSimilarityResultCandidate',
        'properties' => '\Organizeme\Xtractor\Models\InlineResponse200Properties',
        'candidates' => '\Organizeme\Xtractor\Models\ContentSimilarityResultCandidate[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'best_candidate' => 'bestCandidate',
        'properties' => 'properties',
        'candidates' => 'candidates'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'best_candidate' => 'setBestCandidate',
        'properties' => 'setProperties',
        'candidates' => 'setCandidates'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'best_candidate' => 'getBestCandidate',
        'properties' => 'getProperties',
        'candidates' => 'getCandidates'
    );
  
    
    /**
      * $best_candidate 
      * @var \Organizeme\Xtractor\Models\ContentSimilarityResultCandidate
      */
    protected $best_candidate;
    
    /**
      * $properties 
      * @var \Organizeme\Xtractor\Models\InlineResponse200Properties
      */
    protected $properties;
    
    /**
      * $candidates 
      * @var \Organizeme\Xtractor\Models\ContentSimilarityResultCandidate[]
      */
    protected $candidates;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->best_candidate = $data["best_candidate"];
            $this->properties = $data["properties"];
            $this->candidates = $data["candidates"];
        }
    }
    
    /**
     * Gets best_candidate
     * @return \Organizeme\Xtractor\Models\ContentSimilarityResultCandidate
     */
    public function getBestCandidate()
    {
        return $this->best_candidate;
    }
  
    /**
     * Sets best_candidate
     * @param \Organizeme\Xtractor\Models\ContentSimilarityResultCandidate $best_candidate 
     * @return $this
     */
    public function setBestCandidate($best_candidate)
    {
        
        $this->best_candidate = $best_candidate;
        return $this;
    }
    
    /**
     * Gets properties
     * @return \Organizeme\Xtractor\Models\InlineResponse200Properties
     */
    public function getProperties()
    {
        return $this->properties;
    }
  
    /**
     * Sets properties
     * @param \Organizeme\Xtractor\Models\InlineResponse200Properties $properties 
     * @return $this
     */
    public function setProperties($properties)
    {
        
        $this->properties = $properties;
        return $this;
    }
    
    /**
     * Gets candidates
     * @return \Organizeme\Xtractor\Models\ContentSimilarityResultCandidate[]
     */
    public function getCandidates()
    {
        return $this->candidates;
    }
  
    /**
     * Sets candidates
     * @param \Organizeme\Xtractor\Models\ContentSimilarityResultCandidate[] $candidates 
     * @return $this
     */
    public function setCandidates($candidates)
    {
        
        $this->candidates = $candidates;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
