<?php
/**
 * Payload
 *
 * PHP version 5
 *
 * @category Class
 * @package  Organizeme\Xtractor
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Organizeme\Xtractor\Models;

use \ArrayAccess;
/**
 * Payload Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Organizeme\Xtractor
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Payload implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'source' => '\Organizeme\Xtractor\Models\ContentsimilaritySource',
        'candidates' => 'object[]',
        'modifiers' => '\Organizeme\Xtractor\Models\ContentsimilarityModifiers'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'source' => 'source',
        'candidates' => 'candidates',
        'modifiers' => 'modifiers'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'source' => 'setSource',
        'candidates' => 'setCandidates',
        'modifiers' => 'setModifiers'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'source' => 'getSource',
        'candidates' => 'getCandidates',
        'modifiers' => 'getModifiers'
    );
  
    
    /**
      * $source 
      * @var \Organizeme\Xtractor\Models\ContentsimilaritySource
      */
    protected $source;
    
    /**
      * $candidates Object should match structure of source.
      * @var object[]
      */
    protected $candidates;
    
    /**
      * $modifiers 
      * @var \Organizeme\Xtractor\Models\ContentsimilarityModifiers
      */
    protected $modifiers;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->source = $data["source"];
            $this->candidates = $data["candidates"];
            $this->modifiers = $data["modifiers"];
        }
    }
    
    /**
     * Gets source
     * @return \Organizeme\Xtractor\Models\ContentsimilaritySource
     */
    public function getSource()
    {
        return $this->source;
    }
  
    /**
     * Sets source
     * @param \Organizeme\Xtractor\Models\ContentsimilaritySource $source 
     * @return $this
     */
    public function setSource($source)
    {
        
        $this->source = $source;
        return $this;
    }
    
    /**
     * Gets candidates
     * @return object[]
     */
    public function getCandidates()
    {
        return $this->candidates;
    }
  
    /**
     * Sets candidates
     * @param object[] $candidates Object should match structure of source.
     * @return $this
     */
    public function setCandidates($candidates)
    {
        
        $this->candidates = $candidates;
        return $this;
    }
    
    /**
     * Gets modifiers
     * @return \Organizeme\Xtractor\Models\ContentsimilarityModifiers
     */
    public function getModifiers()
    {
        return $this->modifiers;
    }
  
    /**
     * Sets modifiers
     * @param \Organizeme\Xtractor\Models\ContentsimilarityModifiers $modifiers 
     * @return $this
     */
    public function setModifiers($modifiers)
    {
        
        $this->modifiers = $modifiers;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
